export declare const VERSION = "nextworld-1.2.0";
interface ISlidePlayerOptions {
    interval?: number;
    includePicture?: boolean;
    dotsSelector?: string;
    autoCreateDots?: boolean;
    startPaused?: boolean;
    enableBusEvents?: boolean;
    autoplay?: boolean;
    debug?: boolean;
}
export declare class SlidePlayer {
    static readonly SWIPE_THRESHOLD = 50;
    static readonly VERTICAL_TOLERANCE = 30;
    static readonly DEFAULT_INTERVAL = 5000;
    private container;
    private interval;
    private includePicture;
    private dotsSelector;
    private autoCreateDots;
    private enableBusEvents;
    private autoplay;
    private debug;
    private slides;
    private dots;
    private dotsWrapper;
    private currentIndex;
    private lastTickTime;
    private isDestroyed;
    private isPointerDown;
    private pointerStartX;
    private pointerStartY;
    private pointerEndX;
    private pointerEndY;
    private pauseReasons;
    private loader;
    private binder;
    private animateCallback;
    private lastPauseState;
    readonly ready: Promise<void>;
    initError: unknown;
    constructor(containerOrSelector: string | HTMLElement, { interval, includePicture, dotsSelector, autoCreateDots, startPaused, enableBusEvents, autoplay, debug }?: ISlidePlayerOptions);
    private log;
    private resolveContainer;
    private init;
    private animate;
    private togglePause;
    private emitPauseResumeIfChanged;
    play(): void;
    pause(): void;
    isPaused(): boolean;
    goToSlide(index: number, restart?: boolean): void;
    next(restart?: boolean): void;
    prev(restart?: boolean): void;
    private refreshSlides;
    private setupDots;
    private updateDots;
    private setActiveSlide;
    private resetTimer;
    private bindEvents;
    private bindPointerEvents;
    private bindKeyboardEvents;
    private bindVisibilityEvents;
    private bindActivityEvents;
    private bindUnloadEvent;
    private handleSwipe;
    private emit;
    destroy(): void;
    get currentSlideIndex(): number;
    get slideCount(): number;
}
export {};
