export const APP_CONTRACT = {
  name: "Spaceface",
  sourceDir: "public",
  outputDir: "docs",
  defaults: {
    attractorSceneRotateMs: 2400,
    screensaverIdleMs: 60000,
    screensaverDefaultScene: "floating-images",
    screensaverScenePartialUrls: {
      "floating-images": "./resources/features/screensaver-scenes/floating-images.html",
      attractor: "./resources/features/screensaver-scenes/attractor.html",
    },
    slideshowAutoplayMs: 5000,
  },
  pageHooks: ["html[data-mode]", "body[data-page]", "[data-nav-link]"],
  activityInputs: ["mousemove", "wheel", "keydown", "pointerdown", "visibilitychange"],
  partialAssetAttributes: ["src", "poster", "data-src"],
  features: [
    {
      id: "slideshow",
      featureId: "slideshow",
      root: 'data-feature="slideshow"',
      internals: ["[data-slide]", "[data-slide-prev]", "[data-slide-next]"],
    },
    {
      id: "slideplayer",
      featureId: "slideplayer",
      root: 'data-feature="slideplayer"',
      internals: [
        "[data-slideplayer-stage]",
        "[data-slideplayer-slide]",
        "[data-slideplayer-prev]",
        "[data-slideplayer-next]",
        "[data-slideplayer-bullets]",
        "[data-slideplayer-bullet]",
      ],
      singletonNote: "Exactly one slideplayer per page; smoke validation fails duplicates and runtime warns on extra mounts.",
    },
    {
      id: "floating-images",
      featureId: "floating-images",
      root: 'data-feature="floating-images"',
      internals: ["[data-floating-item]"],
    },
    {
      id: "attractor-scene",
      featureId: "attractor-scene",
      root: 'data-feature="attractor-scene"',
      internals: [
        "[data-attractor-scene]",
        "[data-attractor-scene-layout]",
        "[data-attractor-scene-width]",
        "[data-attractor-scene-height]",
        "[data-attractor-scene-year]",
      ],
    },
    {
      id: "portfolio-stage",
      featureId: "portfolio-stage",
      root: 'data-feature="portfolio-stage"',
      internals: [
        "[data-portfolio-stage-stage]",
        "[data-portfolio-stage-item]",
        "[data-portfolio-stage-title]",
        "[data-portfolio-stage-category]",
        "[data-portfolio-stage-summary]",
        "[data-portfolio-stage-prev]",
        "[data-portfolio-stage-next]",
        "[data-portfolio-stage-filter]",
        "[data-portfolio-stage-filter-value]",
        "[data-portfolio-stage-slot]",
        "[data-portfolio-stage-wrap-enter]",
        "[data-portfolio-stage-current-title]",
        "[data-portfolio-stage-current-category]",
        "[data-portfolio-stage-current-index]",
        "[data-portfolio-stage-current-summary]",
        "[data-portfolio-stage-details-toggle]",
        "[data-portfolio-stage-details]",
      ],
      singletonNote: "Exactly one portfolio-stage per page; smoke validation fails duplicates and runtime warns on extra mounts.",
    },
    {
      id: "screensaver",
      featureId: "screensaver",
      root: 'data-feature="screensaver"',
      internals: [
        "[data-screensaver]",
        "[data-screensaver-scene]",
        "[data-screensaver-idle-ms]",
        "[data-screensaver-partial]",
      ],
      singletonNote: "Exactly one screensaver per page; smoke validation fails duplicates and runtime warns on extra mounts.",
    },
  ],
  routes: [
    {
      id: "index",
      file: "index.html",
      page: "index",
      navLabel: "Home",
      featureIds: ["slideshow", "floating-images", "screensaver"],
      hooks: [],
    },
    {
      id: "slideplayer",
      file: "slideplayer.html",
      page: "slideplayer",
      navLabel: "Slideplayer",
      featureIds: ["slideplayer", "screensaver"],
      hooks: [
        { selector: "[data-slideplayer-stage]", presence: "required" },
        { selector: "[data-slideplayer-prev]", presence: "required" },
        { selector: "[data-slideplayer-next]", presence: "required" },
        { selector: "[data-slideplayer-slide]", presence: "required" },
        { selector: "[data-slideplayer-bullets]", presence: "optional" },
      ],
    },
    {
      id: "floatingimages",
      file: "floatingimages.html",
      page: "floatingimages",
      navLabel: "Floating images",
      featureIds: ["floating-images", "screensaver"],
      hooks: [],
    },
    {
      id: "portfoliostage",
      file: "portfoliostage.html",
      page: "portfoliostage",
      navLabel: "Portfolio stage",
      featureIds: ["portfolio-stage", "screensaver"],
      hooks: [
        { selector: "[data-portfolio-stage-stage]", presence: "required" },
        { selector: "[data-portfolio-stage-item]", presence: "required" },
        { selector: "[data-portfolio-stage-prev]", presence: "required" },
        { selector: "[data-portfolio-stage-next]", presence: "required" },
        { selector: "[data-portfolio-stage-filter]", presence: "optional" },
        { selector: "[data-portfolio-stage-details-toggle]", presence: "optional" },
        { selector: "[data-portfolio-stage-details]", presence: "optional" },
      ],
    },
  ],
  partials: [
    {
      id: "screensaver-scene-attractor",
      file: "resources/features/screensaver-scenes/attractor.html",
      hostHook: "[data-screensaver-partial]",
      featureIds: ["attractor-scene"],
      hooks: [
        { selector: "[data-attractor-scene]", presence: "required" },
        { selector: "[data-attractor-scene-layout]", presence: "required" },
        { selector: "[data-attractor-scene-width]", presence: "required" },
        { selector: "[data-attractor-scene-height]", presence: "required" },
        { selector: "[data-attractor-scene-year]", presence: "required" },
        { selector: 'class="attractor-scene"', presence: "required" },
      ],
    },
    {
      id: "screensaver-scene-floating-images",
      file: "resources/features/screensaver-scenes/floating-images.html",
      hostHook: "[data-screensaver-partial]",
      featureIds: ["floating-images"],
      hooks: [
        { selector: "[data-floating-item]", presence: "required" },
        { selector: 'class="screensaver-floating"', presence: "required" },
      ],
    },
  ],
};
