export const APP_CONTRACT = {
  name: "Spaceface",
  sourceDir: "public",
  outputDir: "docs",
  defaults: {
    screensaverIdleMs: 60000,
    slideshowAutoplayMs: 5000,
    screensaverPartialUrl: "./resources/features/screensaver/index.html",
  },
  pageHooks: ["html[data-mode]", "body[data-page]", "[data-nav-link]"],
  activityInputs: ["mousemove", "wheel", "keydown", "pointerdown", "visibilitychange"],
  partialAssetAttributes: ["src", "poster", "data-src"],
  features: [
    {
      id: "slideshow",
      selector: "slideshow",
      root: 'data-feature="slideshow"',
      internals: ["[data-slide]", "[data-slide-prev]", "[data-slide-next]"],
    },
    {
      id: "slideplayer",
      selector: "slideplayer",
      root: 'data-feature="slideplayer"',
      internals: [
        "[data-slideplayer-stage]",
        "[data-slideplayer-slide]",
        "[data-slideplayer-prev]",
        "[data-slideplayer-next]",
        "[data-slideplayer-bullets]",
        "[data-slideplayer-bullet]",
      ],
      singletonNote: "Exactly one slideplayer per page; smoke validation fails duplicates and runtime warns on extra mounts.",
    },
    {
      id: "floating-images",
      selector: "floating-images",
      root: 'data-feature="floating-images"',
      internals: ["[data-floating-item]"],
    },
    {
      id: "portfolio-stage",
      selector: "portfolio-stage",
      root: 'data-feature="portfolio-stage"',
      internals: [
        "[data-portfolio-stage-stage]",
        "[data-portfolio-stage-item]",
        "[data-portfolio-stage-prev]",
        "[data-portfolio-stage-next]",
        "[data-portfolio-stage-filter]",
        "[data-portfolio-stage-current-title]",
        "[data-portfolio-stage-current-category]",
        "[data-portfolio-stage-current-index]",
        "[data-portfolio-stage-current-summary]",
        "[data-portfolio-stage-details-toggle]",
        "[data-portfolio-stage-details]",
      ],
      singletonNote: "Exactly one portfolio-stage per page; smoke validation fails duplicates and runtime warns on extra mounts.",
    },
    {
      id: "screensaver",
      selector: "screensaver",
      root: 'data-feature="screensaver"',
      internals: ["[data-screensaver]", "[data-screensaver-partial]"],
    },
  ],
  routes: [
    {
      id: "index",
      file: "index.html",
      page: "index",
      navLabel: "Home",
      featureSelectors: ["slideshow", "floating-images", "screensaver"],
      hooks: [],
    },
    {
      id: "skeleton",
      file: "skeleton.html",
      page: "skeleton",
      navLabel: "Skeleton",
      featureSelectors: ["screensaver"],
      hooks: [],
    },
    {
      id: "slideplayer",
      file: "slideplayer.html",
      page: "slideplayer",
      navLabel: "Slideplayer",
      featureSelectors: ["slideplayer", "screensaver"],
      hooks: [
        { selector: "[data-slideplayer-stage]", presence: "required" },
        { selector: "[data-slideplayer-prev]", presence: "required" },
        { selector: "[data-slideplayer-next]", presence: "required" },
        { selector: "[data-slideplayer-slide]", presence: "required" },
        { selector: "[data-slideplayer-bullets]", presence: "optional" },
      ],
    },
    {
      id: "floatingimages",
      file: "floatingimages.html",
      page: "floatingimages",
      navLabel: "Floating images",
      featureSelectors: ["floating-images", "screensaver"],
      hooks: [],
    },
    {
      id: "portfoliostage",
      file: "portfoliostage.html",
      page: "portfoliostage",
      navLabel: "Portfolio stage",
      featureSelectors: ["portfolio-stage", "screensaver"],
      hooks: [
        { selector: "[data-portfolio-stage-stage]", presence: "required" },
        { selector: "[data-portfolio-stage-item]", presence: "required" },
        { selector: "[data-portfolio-stage-prev]", presence: "required" },
        { selector: "[data-portfolio-stage-next]", presence: "required" },
        { selector: "[data-portfolio-stage-filter]", presence: "optional" },
        { selector: "[data-portfolio-stage-details-toggle]", presence: "optional" },
        { selector: "[data-portfolio-stage-details]", presence: "optional" },
      ],
    },
  ],
  partials: [
    {
      id: "screensaver",
      file: "resources/features/screensaver/index.html",
      hostHook: "[data-screensaver-partial]",
      featureSelectors: ["floating-images"],
      hooks: [
        { selector: "[data-floating-item]", presence: "required" },
        { selector: 'class="screensaver-floating"', presence: "required" },
      ],
    },
  ],
};
