export declare const VERSION: "nextworld-1.2.1";
import { FloatingImage } from './FloatingImage.js';
import { PerformanceMonitor } from '../bin/PerformanceMonitor.js';
import { AsyncImageLoader } from '../bin/AsyncImageLoader.js';
import type { FloatingImagesManagerOptionsInterface, FloatingImagesManagerInterface } from '../../types/features.js';
export declare class FloatingImagesManager implements FloatingImagesManagerInterface {
    readonly container: HTMLElement;
    performanceMonitor: PerformanceMonitor;
    images: FloatingImage[];
    speedMultiplier: number;
    isInViewport: boolean;
    private _destroyed;
    private animateCallback;
    maxImages: number;
    intersectionObserver: IntersectionObserver;
    unsubscribeWindow?: () => void;
    unsubscribeElement?: () => void;
    imageLoader: AsyncImageLoader;
    containerWidth: number;
    containerHeight: number;
    debug: boolean;
    constructor(container: HTMLElement, options?: FloatingImagesManagerOptionsInterface);
    private setupResizeHandling;
    private updateContainerDimensions;
    private initializeImages;
    private addExistingImage;
    private handleResize;
    private animate;
    private pauseLoop;
    private resumeLoop;
    resetAllImagePositions(): void;
    reinitializeImages(): void;
    destroy(): void;
}
