export declare const VERSION: "2.0.0";
import { FloatingImage } from './FloatingImage.js';
import { PerformanceMonitor } from '../bin/PerformanceMonitor.js';
import { AsyncImageLoader } from '../bin/AsyncImageLoader.js';
import type { FloatingImagesManagerOptionsInterface, FloatingImagesManagerInterface } from '../../types/features.js';
export declare class FloatingImagesManager implements FloatingImagesManagerInterface {
    readonly container: HTMLElement;
    performanceMonitor: PerformanceMonitor;
    images: FloatingImage[];
    speedMultiplier: number;
    isInViewport: boolean;
    private _destroyed;
    private animateCallback;
    maxImages: number;
    intersectionObserver: IntersectionObserver;
    unsubscribeWindow?: () => void;
    unsubscribeElement?: () => void;
    imageLoader: AsyncImageLoader;
    containerWidth: number;
    containerHeight: number;
    debug: boolean;
    hoverBehavior: 'none' | 'slow' | 'stop';
    hoverSlowMultiplier: number;
    tapToFreeze: boolean;
    private interactionCleanups;
    private frozenElements;
    private imageSpeedOverrides;
    constructor(container: HTMLElement, options?: FloatingImagesManagerOptionsInterface);
    private log;
    private setupResizeHandling;
    private updateContainerDimensions;
    private initializeImages;
    private addExistingImage;
    private handleResize;
    private animate;
    resetAllImagePositions(): void;
    reinitializeImages(): void;
    destroy(): void;
    private bindImageInteraction;
    private unbindImageInteractions;
}
